services:
  - type: web
    name: texas-divorce-database
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python download_db.py && gunicorn app:app
    healthCheckPath: /
